In [81]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [79]:
ds = pd.read_csv('../DataSheets/spam.csv')
ds.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [80]:
ds['Spam'] = ds.Category.apply(lambda x: 1 if x=='spam' else 0)
ds.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [84]:
ds.Message.values               # 1D array

array(['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
       'Ok lar... Joking wif u oni...',
       "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
       ..., 'Pity, * was in mood for that. So...any other suggestions?',
       "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free",
       'Rofl. Its true to its name'], dtype=object)

In [94]:
X_train, X_test, y_train, y_test = train_test_split(ds['Message'], ds['Spam'], test_size=.2)  # ds['Message'] 2D array as input

In [95]:
X_train.shape, X_test.shape

((4457,), (1115,))

In [96]:
X_train[:5]       # X-train[5] X

3420    Do you want a new Video phone? 600 anytime any...
1886    I think asking for a gym is the excuse for laz...
5071    5p 4 alfie Moon's Children in need song on ur ...
3636    It's not that you make me cry. It's just that ...
4585    Noooooooo please. Last thing I need is stress....
Name: Message, dtype: object

In [97]:
X_train[:5].values

array(['Do you want a new Video phone? 600 anytime any network mins 400 Inclusive Video calls AND downloads 5 per week Free delTOMORROW call 08002888812 or reply NOW',
       'I think asking for a gym is the excuse for lazy people. I jog.',
       "5p 4 alfie Moon's Children in need song on ur mob. Tell ur m8s. Txt Tone charity to 8007 for Nokias or Poly charity for polys: zed 08701417012 profit 2 charity.",
       "It's not that you make me cry. It's just that when all our stuff happens on top of everything else, it pushes me over the edge. You don't underdtand how often i cry over my sorry, sorry life.",
       'Noooooooo please. Last thing I need is stress. For once in your life be fair.'],
      dtype=object)

In [98]:
cv = CountVectorizer()

In [99]:
X_train_cv = cv.fit_transform(X_train.values)

In [101]:
X_train_cv = X_train_cv.toarray()

In [102]:
X_train_cv

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [103]:
X_train_cv[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [104]:
X_train_cv.shape

(4457, 7758)

In [106]:
cv.get_feature_names_out().shape

(7758,)

In [107]:
cv.vocabulary_

{'do': 2378,
 'you': 7720,
 'want': 7393,
 'new': 4759,
 'video': 7299,
 'phone': 5198,
 '600': 580,
 'anytime': 1012,
 'any': 1004,
 'network': 4751,
 'mins': 4504,
 '400': 487,
 'inclusive': 3663,
 'calls': 1626,
 'and': 975,
 'downloads': 2437,
 'per': 5156,
 'week': 7452,
 'free': 2998,
 'deltomorrow': 2243,
 'call': 1611,
 '08002888812': 51,
 'or': 4985,
 'reply': 5724,
 'now': 4849,
 'think': 6854,
 'asking': 1104,
 'for': 2955,
 'gym': 3312,
 'is': 3760,
 'the': 6821,
 'excuse': 2713,
 'lazy': 4064,
 'people': 5154,
 'jog': 3848,
 '5p': 572,
 'alfie': 917,
 'moon': 4589,
 'children': 1785,
 'in': 3654,
 'need': 4730,
 'song': 6315,
 'on': 4942,
 'ur': 7215,
 'mob': 4550,
 'tell': 6761,
 'm8s': 4297,
 'txt': 7108,
 'tone': 6972,
 'charity': 1737,
 'to': 6943,
 '8007': 646,
 'nokias': 4811,
 'poly': 5309,
 'polys': 5314,
 'zed': 7750,
 '08701417012': 73,
 'profit': 5458,
 'it': 3771,
 'not': 4835,
 'that': 6818,
 'make': 4334,
 'me': 4415,
 'cry': 2089,
 'just': 3889,
 'when': 749

In [132]:
cv.get_feature_names_out()[7299]

'video'

In [127]:
np.where(X_train_cv[0] != 0)

(array([  51,  487,  580,  975, 1004, 1012, 1611, 1626, 2243, 2378, 2437,
        2998, 3663, 4504, 4751, 4759, 4849, 4985, 5156, 5198, 5724, 7299,
        7393, 7452, 7720], dtype=int64),)

In [131]:
X_train_cv[0][7299]

2

In [113]:
X_train[:4]

3420    Do you want a new Video phone? 600 anytime any...
1886    I think asking for a gym is the excuse for laz...
5071    5p 4 alfie Moon's Children in need song on ur ...
3636    It's not that you make me cry. It's just that ...
Name: Message, dtype: object

In [114]:
X_train[:4][3420]

'Do you want a new Video phone? 600 anytime any network mins 400 Inclusive Video calls AND downloads 5 per week Free delTOMORROW call 08002888812 or reply NOW'